<a href="https://colab.research.google.com/github/sandmman/Aphid/blob/master/Assignment_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ECBM E4040 Neural Networks and Deep Learning 
### Columbia University, Fall 2020.

# ECBM E4040 - Assignment 0 

The assignment is distributed as a jupyter notebook called Assignment 0.ipynb from a github repository (or as a zip file).  Additional instructions and support material for the assignment can be found in file README.md which comes with the assignment and in a set of webpages under https://ecbme4040.github.io/2020_fall/index.html. The assignment uses TensorFlow version 2.2. 

The simplest way to initially see the content of the jupyter notebook file Assignment 0.ipynb is to use Google Colab in the cloud: (i) Use your UNI@columbia.edu account to log into the Colab (https://colab.research.google.com/notebooks/intro.ipynb); (ii) Upload Assignment 0.ipynb, explore and run the file. 

For students who are formally registered into this class at the end of the add/drop period, the assignment requires that students complete the tasks from this Jupyter Notebook while running it on the Google Cloud (GCP) custom image (not Colab, Colab is only a temporary execution method).

Detailed instructions how to submit this assignement/homework will be posted after the add/drop period.

## Welcome to ECBM E4040 Neural Networks & Deep Learning 

This course teaches theory, concepts, modelling and programming techniques. The assignments are focused on practical coding for creating, testing and running deep learning models.

The __assignment 0__ introduces our programming environment and tools, and basic TensorFlow operations.

The assignment consists of the following components:
* Programming environment setup - Google Compute Engine/local machine, Python, TensorFlow.
* Using Jupyter Notebook
* TensorFlow basics
* A demo of a program written in TensorFlow

<p style='color:red'>Cells marked with <strong>'TODO'</strong> need to be completed by students, as a part of the assignment.</p>

Please consult TAs or post your problems/issues on the Piazza site.

## Part 1 - Setting up the Programming Environment

For this course, we use __Python__ as the programming language, and [__TensorFlow__](https://www.tensorflow.org) as the deep learning framework. 

Our course website (https://ecbme4040.github.io/) provides a number of tutorials:
* Local Environment Setup
* Google Compute Engine (GCE) Setup on the Google Cloud Platform (GCP)
* Python Tutorial
* TensorFlow Tutorial
* Linux Tutorial
* Git Commands
* Google Colab - link to Google Collaboratory online tool

<p style='color:red'><strong>TODO:</strong></p>

This list shows the big picure for what students need to do to complete the assignment. Later cells in this jupyter notebook describe the details of the operations that need to be executed as TODO items.

* Create an account on github, and familiarize yourself both with git operations and with Github 

* Execute Assignement0.ipynb in Colab: Fetch the Assignement0.ipynb file (from github), upload it into the Google Colab, and execute it inside the Colab environment. To do this, you need to understand python, and the operation of jypyter notebooks. This step is useful for a quick first execution. Keep the modified Jupyter notebook with your solutions.

* Create your own Google Cloud project and virtual machine (VM) instance in the Google Cloud Platform, by following the tutorial on Google Compute Engine (GCE) Setup. This will be the main and the required mode of operation for all future assignments. Note: working with google cloud requires funding - you can initially use the 300 dollars that everyone gets from Google, after the add/drop period you will be given codes/coupons from the instructors.

* Execute (again) the Assignement0.ipynb within your VM in the Google Cloud. Save the resulting Jupyter Notebook. Take a screenshots of the VM instance from the Google Cloud project dashboard. Take a screenshot of the jupyter notebook when launched from google cloud. The screenshots will need to be submitted as a part of the homework to document that you have successfully launched a cloud instance. The modified jupyter notebook which contains the populate "TODO/SOLUTIONS" portions of the code needs to be submitted.

* (Optional) Set up your local laptop deep learning environment, following the tutorial on the Local Environment Setup. Since the use of Google Cloud requires funding, it is often useful to debug your code locally on a laptop, and to run it remotely in Google Cloud VM.

* (Optional) Knowledge of Python, Linux and Git operations are needed for this course. Doing the tutorials is optional, depending on your prior knowledge of these topics.

* (Optional) Tutorials on TensorFlow are extensive. As you progress with this course, they are an excellent complement to our class.

## Part 2 - How to use Jupyter Notebook - Basics

Jupyter Notebook is an interactive Python programming interface. Jupyter Notebook files have a postfix _.ipynb_, and each file is made up of several blocks of code which are called __cells__. Each cell can be configured as a __coding cell__ or a __Markdown text cell__. Google colab is the easiest installation-free platform to run and familiarize oneself with Jupyter Notebook operations.

Basic instructions:

* The menu bars are located on the top of a notebook.
* To execute a cell, select it, and press `ctrl+Enter`. (You may also try `shift+Enter` and `alt+Enter` to see the difference).
* To switch between code and Markdown, select a cell, and select the mode you want in the dropdown menu in the menu bar.

A full guide to Jupyter Notebook can be accessed in the _Help_ menu in the menu bar. 


In [ ]:
# To test that you understand how to use a coding cell, make this cell output a string 'Hello Jpuyter!'. 
# We've written the code, all you need to do is to execute it.
print('Hello Jupyter!')

Hello Jupyter!


## Part 3 - TensorFlow Basics

TensorFlow is one of the most popular deep learning frameworks. Originally created by Google, it has received a lot of community support. TensorFlow versions before v2.0 (until summer 2019) contained a number of detailed functions for construction of deep learning (neural network) models, and relied on a two-step process for model creation and execution. 
TensorFlow versions 2.0 and beyond focus on simplicity and ease of use, with updates like eager execution, intuitive Keras-based higher-level APIs, and flexible model building on any platform.

In this part, we look at some basic TensorFlow concepts and operations.

In [ ]:
# This cell instals matplotlib tool, directly from Jupyter Notebook. 
# The image which is distributed by TAs with envTF22 lacks this tool, 
# so thereby the installation is required.
# Run the below cell just once after removing the '#' sign before the command.
#!pip install --upgrade matplotlib
print("matplotlib installed")

     |████████████████████████████████| 11.6MB 11.1MB/s 
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2


matplotlib installed


In [ ]:
# Activating TensorFlow in Jupyter Notebook

# Disable some warnings, to simplify the output when running the cells
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import numpy as np

# Import the TensorFlow module
import tensorflow as tf

print('TensorFlow Version=')
print(tf.__version__)

# The following modules will be used in later parts of the assignment.
# Make sure that you install the latest version of numpy and matploblib 
#(inside your conda workspace). Alternativelly, inside your virtual environment, use "conda install numpy" 
# and "conda install matploblib" and restart the jupyter notebook. 
import numpy as np
# import input_data
%matplotlib inline
from matplotlib import pyplot as plt
import time

TensorFlow Version=
2.3.0


#### 1. Use of string constant with TensorFlow

In TensorFlow 2.0 the concept of sessions (as in versions before 2.0) has ben deprecated. Now, variables are accessible instantly (as compared to after sess.run), making this flow "more pythonic in style".

In [ ]:
# Example
# Define a string constant
string = tf.constant('Hello TensorFlow!')
tf.print(string)

Hello TensorFlow!


<p style='color:red'><strong>TODO:</strong></p>

Follow the example above and use TensorFlow to output the string 'YOUR_NAME:YOUR_UNI'. 

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [ ]:
name = tf.constant('aaron_liberatore:aml2322')
tf.print(string)

Hello TensorFlow!


#### 2. Basic math in TensorFlow

In [ ]:
# Example

# Define 2 constant nodes. It is a good habit to name your nodes. 
# The name of the nodes will appear in the TensorBoard graph.
a = tf.constant(5, dtype=tf.float32, name='a')
b = tf.constant(10, dtype=tf.float32, name='b')

# Addition and subtraction
add = tf.add(a, b, name='add') # same as a+b
sub = tf.subtract(a, b, name='sub') # same as a-b

# There is no need for the session to run these operations (as in TensorFlow 1.*)
tf.print("a:", a)
tf.print("b:", b)
tf.print("addition:", add)
tf.print("subtraction:", sub)

a: 5
b: 10
addition: 15
subtraction: -5


<p style='color:red'><strong>TODO:</strong></p>

In [ ]:
# Visit https://www.tensorflow.org/api_guides/python/math_ops 
# Find proper operations to calculate 
# a*b (multiplication), a/b (division), a^b (power) and log(a) (natural logarithm),
# and demonstrate their uses by outputing their results in a session. 
# (Note: 'a' and 'b' are defined in the previous cell, you should use them directly.)

Multiply, 50.0
Divide, 0.5
Power, 9765625.0
Log, 1.6094379425048828


<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [ ]:
m = tf.multiply(a, b)
print("Multiply: {}".format(m))

m = tf.divide(a, b)
print("Divide: {}".format(m))

m = tf.pow(a, b)
print("Power: {}".format(m))

m = tf.math.log(a)
print("Log: {}".format(m))

Multiply: 50.0
Divide: 0.5
Power: 9765625.0
Log: 1.6094379425048828


#### 3. Constant tensor, sequences and random numbers in TensorFlow

In [ ]:
# In TensorFlow, a tensor is an n-dimensional array. 
# 0-d tensor is a scalar. 1-d tensor is a vector, and so on.

# We can use TF functions to create all-zero and all-one tensors.
zero_array = tf.zeros(shape=[2,3], dtype=tf.float32, name='zero_array')
one_array = tf.ones(shape=[2,3], dtype=tf.float32, name='one_array')

# Or use a template to infer the shape.
template = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float32, name='template') # Has [2,3] shape
zero_like = tf.zeros_like(template, name='zero_like')
one_like = tf.ones_like(template, name='one_like')

# Some sequence generating functions
lin_seq = tf.linspace(start=0.0, stop=5.0, num=5, name='lin_seq')
lin_range = tf.range(start=0, limit=7, delta=1, name='lin_range')

# A random number function
norm = tf.random.normal(shape=[5], mean=3, stddev=2.0)

# Printing out
tf.print('0 array:\n', zero_array)
tf.print('1 array:\n', one_array)
tf.print('0 inferred:\n', zero_like)
tf.print('1 inferred:\n', one_like)
tf.print('linear sequence:\n', lin_seq)
tf.print('range:\n', lin_range)
tf.print('Random normal:\n', norm)

0 array:
 [[0 0 0]
 [0 0 0]]
1 array:
 [[1 1 1]
 [1 1 1]]
0 inferred:
 [[0 0 0]
 [0 0 0]]
1 inferred:
 [[1 1 1]
 [1 1 1]]
linear sequence:
 [0 1.25 2.5 3.75 5]
range:
 [0 1 2 ... 4 5 6]
Random normal:
 [1.0519557 3.84575748 2.90249753 -0.407419682 4.41958523]


<p style='color:red'><strong>TODO:</strong></p>

In [ ]:
# 1: Generate a 3*3 matrix filled with 9s. 
# 2: Generate a sequence start from -5.0 to 5.0(inclusive), with step size of 1.0.
# 3: Generate another 3*3 matrix with normal distribution. Choose any mean and stddev you like.
# Hint: Visit https://www.tensorflow.org/api_guides/python/constant_op

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [ ]:
# 1: Generate a 3*3 matrix filled with 9s. 
nine_array = tf.fill(dims=[3,3], value=9, name='nine_array')
print("nine_array: {}".format(nine_array))

# 2: Generate a sequence start from -5.0 to 5.0(inclusive), with step size of 1.0.
range_array = tf.range(start=-5.0, limit=5.0, delta=1, dtype=tf.float32, name='range_array')
print("range_array: {}".format(range))

# 3: Generate another 3*3 matrix with normal distribution. Choose any mean and stddev you like.
normal_matrix = tf.random.normal(
    shape=[3,3], mean=0.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name="normal_matrix"
)
print("normal_matrix: {}".format(normal_matrix))

nine_array: [[9 9 9]
 [9 9 9]
 [9 9 9]]
range_array: [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]
normal_matrix: [[-0.7045955   0.16568285 -0.10914768]
 [-0.75484025  0.01126422 -1.0466362 ]
 [ 1.6686909  -1.2482897  -1.5897906 ]]


#### 4. Variables in TensorFlow

In [ ]:
# The values of constants (previously described) can not be changed. 
# For TensorFlow variables, their values can be updated during the training of a network.

initial_value = tf.Variable([2,3], dtype=tf.float32) # You need to give an initial value to the variable.
tf.print("initial value:", initial_value)

# Several ops that can be used to change the value of a variable. 
# Note that they all become nodes in the graph.
new_value = initial_value.assign([4,5])
tf.print("assigned value:", new_value)
add = initial_value.assign_add([1,1])
tf.print("add:", add)

initial value: [2 3]
assigned value: [4 5]
add: [5 6]


<p style='color:red'><strong>TODO:</strong></p>

In [ ]:
# Create a 3*3 tensor variable (the initial values don't matter).
# Assign values from 1 to 9 to it and than add 1 to each assigned value in the 3*3 tensor.
# Print out the initial values and print out the new values after the assign operation.

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

In [ ]:
# Create a 3*3 tensor variable (the initial values don't matter)
initial_array = tf.Variable(tf.ones(shape=[3,3], name='initial_array'))
print("initial_array: {}".format(initial_array))
# Assign values from 1 to 9 to it and than add 1 to each assigned value in the 3*3 tensor.
assigned_value = initial_array.assign([[1,2,3],[4,5,6],[7,8,9]])
print("assigned_value: {}".format(assigned_value))

added_value = initial_array.assign(initial_array + 1)
print("new_value: {}".format(added_value))


initial_array: <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
assigned_value: <tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>
new_value: <tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>


#### 5. Data type impact

In [ ]:
# In tensorflow, the float type of data includes float32 and float64. 
# In later assignments, 
# you should always consider float32 as the first choice for sake of efficiency, 
# even though the precision is lower than for float64.

# Here we compare the precision difference between these two types.
A32 = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.float32)
B32 = (A32 + 0.1)**2
A64 = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.float64)
B64 = (A64 + 0.1)**2

tf.print('float32 result: \n {}'.format(B32))
tf.print('float64 result: \n {}'.format(B64))

float32 result: 
 [[ 1.21       4.4099994  9.61     ]
 [16.81      26.009998  37.21     ]]
float64 result: 
 [[ 1.21  4.41  9.61]
 [16.81 26.01 37.21]]


#### 6. Distance calculation

$$
Euclidean Norm(l_2)= \sqrt{\sum _{i=1}^{n} \left( q_{i}-p_{i}\right)^2 }
$$
<br>
$$
Manhattan Distance(l_1)= {\sum _{i=1}^{n} \left(|q| - |p|\right) }
$$

In [ ]:
# Distance Calculation 
#
# Create a tensor among the following types : float32, float64, complex64, complex128
# Mentioned link details the meaning of each variable : https://www.tensorflow.org/api_docs/python/tf/norm
     
# create two tensors of shape 2x3.
tensor_a = tf.constant([[1,2,3], [4,5,6]], dtype=tf.float32, name='template')
tensor_b = tf.constant([[1,1,1], [1,1,1]], dtype=tf.float32, name='template')

# 1. Calculating euclidean distance or the l2 norm.

eucledian_distance = tf.norm(tensor_a - tensor_b, ord ='euclidean', axis=None, keepdims=None)
tf.print("Euclidean distance:", eucledian_distance)


# 2. Calculating the Manhattan distance
manhattan_distance = tf.norm(tensor_a - tensor_b, ord =1, axis=None, keepdims=None)
tf.print("Manhattan distance:", manhattan_distance)

<p style='color:red'><strong>TODO:</strong></p>

In [ ]:
# Create two funtions using numpy which will return the eucledian distance and manhattan distance
# between the above mentioned tensors.
# Print out their outputs.

<p style='color:red'><strong>SOLUTION (enter a new cell below):</strong></p>

We have introduced only the basic TensorFlow operations and concepts. We recommend that you visit the TensorFlow tutorial link for many more https://www.tensorflow.org/tutorials. You will need them to be able to efficiently build and execute deep learning models.

## Part 4 - TensorFlow Demos
Part 4 of this assignemnt consists of a demo. All you need to do is to run the demos and observe the results. This is meant to give you an idea of how TensorFlow is used.

Please run the code and look at the outputs. We do not ask you to fully understand the model at this point. However, it would be a good practice if you searched [www.tensorflow.org](https://www.tensorflow.org) to examine the functions which are used in the code. They will be really helpful when you start programming by yourself.

### Demo1: Multiclass Logistic Regression
#### Loading and preparing the MNIST dataset

In [ ]:
# Multi-class Logistic Regression

from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Convert to float32.

x_train, x_test = np.array(x_train, np.float32), np.array(x_test, np.float32)

# Flatten images to 1-D vector of 784 features (28*28).
num_features = 784 
x_train, x_test = x_train.reshape([-1, num_features]), x_test.reshape([-1, num_features])

#Normalize images value from [0, 255] to [0, 1].

x_train, x_test = x_train / 255., x_test / 255. 
print("Cell executed. Move to the next cell")

#### Setting up hyperparameters and dataset parameters

In [ ]:
# MNIST dataset parameters.

num_classes = 10 # 0 to 9 digits
num_features = 784 # 28*28

# Training parameters.

learning_rate = 0.01
training_steps = 1000
batch_size = 256
display_step = 50
print("Cell executed. Move to the next cell")

#### Shuffling and Batching the data

In [ ]:
# Using tf.data API to shuffle and batch data.

train_data=tf.data.Dataset.from_tensor_slices((x_train,y_train))

train_data=train_data.repeat().shuffle(5000).batch(batch_size).prefetch(1)
print("Cell executed. Move to the next cell")

#### Initializing weights and biases

In [ ]:
# Weight of shape [784, 10], the 28*28 image features, and a total number of classes.
W = tf.Variable(tf.ones([num_features, num_classes]), name="weight")

# Bias of shape [10], the total number of classes.
b = tf.Variable(tf.zeros([num_classes]), name="bias")
print("Cell executed. Move to the next cell")

#### Defining Logisitic Regression and Cost function

In [ ]:
# Logistic regression (Wx + b).
def logistic_regression(x):
    # Apply softmax to normalize the logits to a probability distribution.
    return tf.nn.softmax(tf.matmul(x, W) + b)

# Cross-Entropy loss function.
def cross_entropy(y_pred, y_true):
    # Encode label to a one hot vector.
    y_true = tf.one_hot(y_true, depth=num_classes)

    # Clip prediction values to avoid log(0) error.
    y_pred = tf.clip_by_value(y_pred, 1e-9, 1.)

    # Compute cross-entropy.
    return tf.reduce_mean(-tf.reduce_sum(y_true * tf.math.log(y_pred)))
print("Cell executed. Move to the next cell")

#### Defining Optimizers and Accuracy Metrics

In [ ]:
# Accuracy metric.
def accuracy(y_pred, y_true):
    # Predicted class is the index of the highest score in prediction vector (i.e. argmax).

    correct_prediction = tf.equal(tf.argmax(y_pred, 1), tf.cast(y_true, tf.int64))

    return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# Stochastic gradient descent optimizer.
optimizer = tf.optimizers.SGD(learning_rate)
print("Cell executed. Move to the next cell")

#### Optimization process and Updating Weights and Biases

In [ ]:
# Optimization process. 

def run_optimization(x, y):
    # Wrap computation inside a GradientTape for automatic differentiation.
    with tf.GradientTape() as g:
        pred = logistic_regression(x)
        loss = cross_entropy(pred, y)
    # Compute gradients.
    gradients = g.gradient(loss, [W, b])

    # Update W and b following gradients.
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    
# printf
print("Cell executed. Move to the next cell")


#### Training loop

In [ ]:
# Run training for the given number of steps.

print("This cell should run and show output for 1000 steps. Running ...")

for step, (batch_x, batch_y) in enumerate(train_data.take(training_steps), 1):
    # Run the optimization to update W and b values.
    run_optimization(batch_x, batch_y)
    if step % display_step == 0:
        pred = logistic_regression(batch_x)
        loss = cross_entropy(pred, batch_y)
        acc = accuracy(pred, batch_y)
        print("step: %i, loss: %f, accuracy: %f" % (step, loss, acc))
        
print("Cell executed. Move to the next cell")

#### Testing model accuracy using the testing data

In [ ]:
# Test model on validation set.
pred = logistic_regression(x_test)
print("Test Accuracy: %f" % accuracy(pred, y_test))

## Part 5 - Organizing the Code for Development of Deep Leaning Models
This assignment was distributed as a collection of directories and files (either through the github/bitbucket or a collection of files in a *.zip package).
The organization of directories and files is described in the corresponding README file, and illustrated below as well:
<p style='color:red'><strong>TODO Study the organization of directories and files for this assignment</strong></p>
 - In particular examine the way in which jupyter notebook files and utility python files are distributed accross directories. Students will be required to follow this (or very similar) directory structure for their assignments and projects. For every project/assignment, a similar tree structure needs to be generated and appended to the README file.

A typical organization of the top directory as of 8/24/2020 can be seen at the end of the README.md file.

### Steps to create and visualize the tree-like directory structure:
<p style='color:red'><strong>1. For Linux:</strong></p>

a. Go to the directory for which you want to create and visualize the tree structure for.

b. Type : !tree -a >> README.md in the jupyter notebook - This will append the tree to the README.md file in the same directory.

c.  After running the above command make the following changes:

- Go to the README.md and remove the below mentioned lines 
"Folder PATH listing for volume DATA
Volume serial number is 0A8A-1CBE
D:\CA_4040\MASTER_BRANCH\E4040-2020FALL-ASSIGNMENTSALL-INSTRUCTORVERSION\ASSIGNMENT0.SOLUTION"

- then, manually enclose the whole appended text in 3 single quotes (inverted quote ```) at the top and the bottom with the same indentation. (Look at the the example mentioned below)
 
<p style='color:red'><strong>2. For Windows:</strong></p>

a. Go to the directory that you want the tree structure for.

b. Type : !tree ./ /f /a >> README.md in the jupyter notebook - This will append the tree to the README.md file in the same directory.

c.  After running the above command make below mentioned changes:

- Go to the README.md and remove the below mentioned lines 
"Folder PATH listing for volume DATA
Volume serial number is 0A8A-1CBE
D:\CA_4040\MASTER_BRANCH\E4040-2020FALL-ASSIGNMENTSALL-INSTRUCTORVERSION\ASSIGNMENT0.SOLUTION"

- Then, manually enclose the whole appended text within 3 single quotes (inverted quote ```) at the top and the bottom with the same indentation. (Look at the the example mentioned below)

d. NOTE:The two chevrons >> are used to append the output of a command to the bottom of a file (instead of one chevron which overwrites the file).


## Submission of the Assignment
The method of the submission and the naming are described in the README.md file, distributed in Github. For formal submission, additional instructions will be provided a few days before the assignment is due.

## End of the assignment